version: '3'
services:

  web:
    image: nginx:alpine
    ports:
      - '8080:80'
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: exampleuser
      POSTGRES_PASSWORD: examplepass
