version: "3.7"
services:
#Configuracion del Zookepper
  zookeeper:
    container_name: zookepper
    image: docker.io/bitnami/zookeeper:3.9
    environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
    ports:
      - "2181:2181"
      - "2888:2888"
#Configuracion del Kafka
  kafka:
    container_name: kafka
    image: docker.io/bitnami/kafka:3.4
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
      BROKER_ID: 1
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
#Configuracion de la BD MySQL
  mysql:
    container_name: mysql
    image: quay.io/debezium/example-mysql:2.7
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
#Configuracion del Conector
  connect:
    container_name: connect
    image: quay.io/debezium/connect:2.7
    ports:
      - 8083:8083
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      BOOTSTRAP_SERVERS: kafka:9092